### ISSUE TITLE
access to NAI3?

### ISSUE THREAD

**Issue by ghost** [HanaokaYuzu/NovelAI-API#10]
is it possible to acces to NAI3 via API? my result  are very different even I used model `nai-diffusion-3`

![image](https://github.com/HanaokaYuzu/NovelAI-API/assets/134971595/7d58248f-c4fc-4bff-bca3-be65a60d7a9f)

![image](https://github.com/HanaokaYuzu/NovelAI-API/assets/134971595/cef3ad85-28f0-442c-83fc-e6f1a1c4d951)

**Comment by ghost** [comment]
this is my payload
![image](https://github.com/HanaokaYuzu/NovelAI-API/assets/134971595/1a3b6464-64e5-4473-a8ee-0c5a5188a0ba)

**Comment by HanaokaYuzu** [comment]
`nai-diffusion-3` is exactly the same model as "NAI Diffusion Anime V3" on the website. You may want to check if you are using the same resolution and tag presets. Btw SMEA (`sm` param in `Metadata`) is enabled by default in API, but not on website when you choose "small" or "normal" resolutions.

<img width="339" alt="image" src="https://github.com/HanaokaYuzu/NovelAI-API/assets/157540577/c3b6682c-bcc2-4ea8-a217-d3184b26a833">
