### ISSUE TITLE
Unable to perform Initialization

### ISSUE THREAD

**Issue by Awakumori** [HanaokaYuzu/NovelAI-API#11]
Hello.

I tried to perform Initialization using the email and password for logging into https://novelai.net/image. However, I always encounter the following error: *novelai.exceptions.AuthError: Access token is incorrect. Message from NovelAI: Incorrect access key.*

I attempted to verify the correctness of my email and password using the *python -m novelai_api get_access_key username password* function from https://github.com/Aedial/novelai-api and found that they are correct. Therefore, I don't understand why I am unable to log in successfully during Initialization.

**Comment by HanaokaYuzu** [comment]
This package is lack of maintenance and will be archived since i'm no longer subscribing to their service. Please look for other alternatives, sorry.
