### ISSUE TITLE
Will concurrent generation result in account ban?

### ISSUE THREAD

**Issue by ShowLemon** [HanaokaYuzu/NovelAI-API#4]
I heard that concurrent generation functionality could lead to account bans. Have you encountered this while using it?
What suggestions do you have to avoid account bans?

**Comment by HanaokaYuzu** [comment]
Never happens to me. But unfortunately, NovelAI is going to block generating image from the API endpoint starting from Mar 21, so...just enjoy the last chance of concurrent generation👋

Source: https://fxtwitter.com/novelaiofficial/status/1760404186066227673
