### ISSUE TITLE
Can additional Samplers be supported?

### ISSUE THREAD

**Issue by Container-Zero** [HanaokaYuzu/NovelAI-API#5]
Supported samplers on the v3 website include: `k_euler`, `k_euler_ancestral`, `k_dpmpp_2s_ancestral`, `ddim_v3`, `k_dpmpp_2m`, `k_dpmpp_sde`.

But it doesn't seem to be possible to use the last three, which results in the error:
 `Input should be 'k_euler', 'k_euler_ancestral' or 'k_dpmpp_2s_ancestral'`

Is it possible to support sampler support for `ddim_v3`, `k_dpmpp_2m`, `k_dpmpp_sde`?

**Comment by HanaokaYuzu** [comment]
Added `ddim_v3`, `k_dpmpp_2m` and `k_dpmpp_sde` to `constant.Sampler` in v1.2.0
