### ISSUE TITLE
Issue with import

### ISSUE THREAD

**Issue by a-pretty-parrot** [HanaokaYuzu/NovelAI-API#7]
When I cloned repo locally, i had no problem doing 
`from novelai import Resolution, Sampler`

But when I finished my debugging and went back to the pip version it didnt work anymore.
I found in my `site-packages/novelai` `constant.py` became `consts.py` and the contents are like `RESOLUTIONS`.

to fix i simply changed to `from novelai import NAIClient, Metadata, RESOLUTIONS, MODELS, SAMPLERS`

and it worked fine.

I dont know much about actually making modules so I dont know how to fix, but very handy nice module so wanted to help make it better so README aligns with everything :>

**Comment by HanaokaYuzu** [comment]
The reason is you installed an older version of this library with pip. Please run `pip install -U novelai` to update the library to latest version (1.2.0) and try again.

**Comment by a-pretty-parrot** [comment]
I completely missed that sorry.

works now :>

thank you
