### ISSUE TITLE
Does it automatically set 'add quality tags' by default?

### ISSUE THREAD

**Issue by RobinAlc** [HanaokaYuzu/NovelAI-API#8]
Sometimes, I notice that the outputs differ from those generated directly on the website using the same prompt. How to open or close the setting 'add quality tags'? And how can I adjust parameters such as guidance?

**Comment by HanaokaYuzu** [comment]
All generation parameters can be configured on creating `Metadata` object. Please refer to the [docstring of `Metadata` class](https://github.com/HanaokaYuzu/NovelAI-API/blob/master/src/novelai/types/metadata.py).

For example, the following code will disable "add quality tags" and set guidance value to 5.5.
```python
metadata = Metadata(prompt="one girl", qualityToggle=False, scale=5.5)
```
