### ISSUE TITLE
Some of the parameter types on the Novelai website have been updated, and some of the parameters no longer work.

### ISSUE THREAD

**Issue by Container-Zero** [HanaokaYuzu/NovelAI-API#9]
`reference_image: str -> list`
`reference_strength: float -> list`
`reference_infomation_extracted: float -> list`

It is now known that the above three parameters have been changed to the list type, and the `v1.2.0` version of the code no longer works properly, and it is not yet known if the other parameters have undergone a type update.

**Comment by HanaokaYuzu** [comment]
Fixed in v1.3.0. The names of these three parameters have been updated. Please note that any old code using the previous names will need to be revised accordingly.
